apiVersion: v1
kind: Secret
metadata:
  name: secret-food
type: Opaque
stringData:
  APPLICATION_VERSION: latest
  APPLICATION_DATABASE_VERSION: latest
  MYSQL_ROOT_PASSWORD: rootpedidos
  MYSQL_DATABASE: pedidos
  MYSQL_USER: pedidos
  MYSQL_PASSWORD: pedidos
  SPRING_DATASOURCE_USERNAME: pedidos
  SPRING_DATASOURCE_PASSWORD: pedidos