version: "2.26"

volumes:
  mysql_data: {}

services:
  mysqlclientedb:
    image: mysql:8.0
    volumes: 
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - foodapi-network
    restart: always
    env_file:
      - config/env/test.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  springboot-app:
    image: springboot-app
    networks:
      - foodapi-network
    env_file:
      - config/env/test.env
    build: .
    depends_on:
      mysqlclientedb:
        condition: service_healthy
    ports:
      - "8082:8082"
networks:
  foodapi-network: