apiVersion: v1
kind: Service
metadata:
  name: svc-food
spec:
  type: NodePort
  # type: LoadBalancer // Quando for na AWS
  selector:
    app: deployment-food-app
  ports:
    - port: 8080
      nodePort: 30001