# Para termos um HPA (Horizontal Pod Autoscaling), precisamos de um servidor de métricas.
# Para isso, usamos um diretamente definido pelo Kubernetes (veja o arquivo metrics-server.yaml)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-pod-food
spec:
  # Qual é o Deployment alvo
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-food
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Baseado em Milicores
          averageUtilization: 50