apiVersion: v1
kind: Pod
metadata:
  name: pod-food
  labels:
    app: pod-food
spec:
  containers:
    - name: pod-food-container
      image: carlohcs/food-repo:6
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: cm-food
        - secretRef:
            name: secret-food
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      # resources:
      #   requests:
      #     cpu: "16m"
      #     memory: "256Mi"
      #   limits:
      #     cpu: "300m"
      #     memory: "550Mi"