apiVersion: v1
kind: Service
metadata:
  name: svc-db-food
  labels:
    app: svc-db-food
spec:
  ports:
  - port: 3306
    nodePort: 31006
    name: svc-db-food
  # clusterIP: None
  type: NodePort
  selector:
    app: statefulset-db-food